using Microsoft.Maui.Controls;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BlueSkyApp.Resources.Styles;

partial class ApplicationTheme
{
    public static class Brushes
    {
        public static class Global
        {
            public static class Light
            {
                public static SolidColorBrush White { get; } = new SolidColorBrush(Colors.Global.Light.White);
                public static SolidColorBrush Grey10 { get; } = new SolidColorBrush(Colors.Global.Light.Grey10);
                public static SolidColorBrush Grey20 { get; } = new SolidColorBrush(Colors.Global.Light.Grey20);
                public static SolidColorBrush Grey30 { get; } = new SolidColorBrush(Colors.Global.Light.Grey30);
                public static SolidColorBrush Grey40 { get; } = new SolidColorBrush(Colors.Global.Light.Grey40);
                public static SolidColorBrush Grey50 { get; } = new SolidColorBrush(Colors.Global.Light.Grey50);
                public static SolidColorBrush Grey60 { get; } = new SolidColorBrush(Colors.Global.Light.Grey60);
                public static SolidColorBrush Grey70 { get; } = new SolidColorBrush(Colors.Global.Light.Grey70);
                public static SolidColorBrush Grey80 { get; } = new SolidColorBrush(Colors.Global.Light.Grey80);
                public static SolidColorBrush Grey90 { get; } = new SolidColorBrush(Colors.Global.Light.Grey90);
                public static SolidColorBrush Grey100 { get; } = new SolidColorBrush(Colors.Global.Light.Grey100);
                public static SolidColorBrush Brand10 { get; } = new SolidColorBrush(Colors.Global.Light.Brand10);
                public static SolidColorBrush Brand20 { get; } = new SolidColorBrush(Colors.Global.Light.Brand20);
                public static SolidColorBrush Brand30 { get; } = new SolidColorBrush(Colors.Global.Light.Brand30);
                public static SolidColorBrush Brand40 { get; } = new SolidColorBrush(Colors.Global.Light.Brand40);
                public static SolidColorBrush Brand50 { get; } = new SolidColorBrush(Colors.Global.Light.Brand50);
                public static SolidColorBrush Brand60 { get; } = new SolidColorBrush(Colors.Global.Light.Brand60);
                public static SolidColorBrush Brand70 { get; } = new SolidColorBrush(Colors.Global.Light.Brand70);
                public static SolidColorBrush Brand80 { get; } = new SolidColorBrush(Colors.Global.Light.Brand80);
                public static SolidColorBrush Brand90 { get; } = new SolidColorBrush(Colors.Global.Light.Brand90);
                public static SolidColorBrush Brand100 { get; } = new SolidColorBrush(Colors.Global.Light.Brand100);
                public static SolidColorBrush Green10 { get; } = new SolidColorBrush(Colors.Global.Light.Green10);
                public static SolidColorBrush Green20 { get; } = new SolidColorBrush(Colors.Global.Light.Green20);
                public static SolidColorBrush Green30 { get; } = new SolidColorBrush(Colors.Global.Light.Green30);
                public static SolidColorBrush Green40 { get; } = new SolidColorBrush(Colors.Global.Light.Green40);
                public static SolidColorBrush Green50 { get; } = new SolidColorBrush(Colors.Global.Light.Green50);
                public static SolidColorBrush Green60 { get; } = new SolidColorBrush(Colors.Global.Light.Green60);
                public static SolidColorBrush Green70 { get; } = new SolidColorBrush(Colors.Global.Light.Green70);
                public static SolidColorBrush Green80 { get; } = new SolidColorBrush(Colors.Global.Light.Green80);
                public static SolidColorBrush Green90 { get; } = new SolidColorBrush(Colors.Global.Light.Green90);
                public static SolidColorBrush Green100 { get; } = new SolidColorBrush(Colors.Global.Light.Green100);
                public static SolidColorBrush Yellow10 { get; } = new SolidColorBrush(Colors.Global.Light.Yellow10);
                public static SolidColorBrush Yellow20 { get; } = new SolidColorBrush(Colors.Global.Light.Yellow20);
                public static SolidColorBrush Yellow30 { get; } = new SolidColorBrush(Colors.Global.Light.Yellow30);
                public static SolidColorBrush Yellow40 { get; } = new SolidColorBrush(Colors.Global.Light.Yellow40);
                public static SolidColorBrush Yellow50 { get; } = new SolidColorBrush(Colors.Global.Light.Yellow50);
                public static SolidColorBrush Yellow60 { get; } = new SolidColorBrush(Colors.Global.Light.Yellow60);
                public static SolidColorBrush Yellow70 { get; } = new SolidColorBrush(Colors.Global.Light.Yellow70);
                public static SolidColorBrush Yellow80 { get; } = new SolidColorBrush(Colors.Global.Light.Yellow80);
                public static SolidColorBrush Yellow90 { get; } = new SolidColorBrush(Colors.Global.Light.Yellow90);
                public static SolidColorBrush Yellow100 { get; } = new SolidColorBrush(Colors.Global.Light.Yellow100);
                public static SolidColorBrush Red10 { get; } = new SolidColorBrush(Colors.Global.Light.Red10);
                public static SolidColorBrush Red20 { get; } = new SolidColorBrush(Colors.Global.Light.Red20);
                public static SolidColorBrush Red30 { get; } = new SolidColorBrush(Colors.Global.Light.Red30);
                public static SolidColorBrush Red40 { get; } = new SolidColorBrush(Colors.Global.Light.Red40);
                public static SolidColorBrush Red50 { get; } = new SolidColorBrush(Colors.Global.Light.Red50);
                public static SolidColorBrush Red60 { get; } = new SolidColorBrush(Colors.Global.Light.Red60);
                public static SolidColorBrush Red70 { get; } = new SolidColorBrush(Colors.Global.Light.Red70);
                public static SolidColorBrush Red80 { get; } = new SolidColorBrush(Colors.Global.Light.Red80);
                public static SolidColorBrush Red90 { get; } = new SolidColorBrush(Colors.Global.Light.Red90);
                public static SolidColorBrush Red100 { get; } = new SolidColorBrush(Colors.Global.Light.Red100);
                public static SolidColorBrush Blue10 { get; } = new SolidColorBrush(Colors.Global.Light.Blue10);
                public static SolidColorBrush Blue20 { get; } = new SolidColorBrush(Colors.Global.Light.Blue20);
                public static SolidColorBrush Blue30 { get; } = new SolidColorBrush(Colors.Global.Light.Blue30);
                public static SolidColorBrush Blue40 { get; } = new SolidColorBrush(Colors.Global.Light.Blue40);
                public static SolidColorBrush Blue50 { get; } = new SolidColorBrush(Colors.Global.Light.Blue50);
                public static SolidColorBrush Blue60 { get; } = new SolidColorBrush(Colors.Global.Light.Blue60);
                public static SolidColorBrush Blue70 { get; } = new SolidColorBrush(Colors.Global.Light.Blue70);
                public static SolidColorBrush Blue80 { get; } = new SolidColorBrush(Colors.Global.Light.Blue80);
                public static SolidColorBrush Blue90 { get; } = new SolidColorBrush(Colors.Global.Light.Blue90);
                public static SolidColorBrush Blue100 { get; } = new SolidColorBrush(Colors.Global.Light.Blue100);
            }

            public static class Dark
            {
                public static SolidColorBrush White { get; } = new SolidColorBrush(Colors.Global.Dark.White);
                public static SolidColorBrush Grey10 { get; } = new SolidColorBrush(Colors.Global.Dark.Grey10);
                public static SolidColorBrush Grey20 { get; } = new SolidColorBrush(Colors.Global.Dark.Grey20);
                public static SolidColorBrush Grey30 { get; } = new SolidColorBrush(Colors.Global.Dark.Grey30);
                public static SolidColorBrush Grey40 { get; } = new SolidColorBrush(Colors.Global.Dark.Grey40);
                public static SolidColorBrush Grey50 { get; } = new SolidColorBrush(Colors.Global.Dark.Grey50);
                public static SolidColorBrush Grey60 { get; } = new SolidColorBrush(Colors.Global.Dark.Grey60);
                public static SolidColorBrush Grey70 { get; } = new SolidColorBrush(Colors.Global.Dark.Grey70);
                public static SolidColorBrush Grey80 { get; } = new SolidColorBrush(Colors.Global.Dark.Grey80);
                public static SolidColorBrush Grey90 { get; } = new SolidColorBrush(Colors.Global.Dark.Grey90);
                public static SolidColorBrush Grey100 { get; } = new SolidColorBrush(Colors.Global.Dark.Grey100);
                public static SolidColorBrush Brand10 { get; } = new SolidColorBrush(Colors.Global.Dark.Brand10);
                public static SolidColorBrush Brand20 { get; } = new SolidColorBrush(Colors.Global.Dark.Brand20);
                public static SolidColorBrush Brand30 { get; } = new SolidColorBrush(Colors.Global.Dark.Brand30);
                public static SolidColorBrush Brand40 { get; } = new SolidColorBrush(Colors.Global.Dark.Brand40);
                public static SolidColorBrush Brand50 { get; } = new SolidColorBrush(Colors.Global.Dark.Brand50);
                public static SolidColorBrush Brand60 { get; } = new SolidColorBrush(Colors.Global.Dark.Brand60);
                public static SolidColorBrush Brand70 { get; } = new SolidColorBrush(Colors.Global.Dark.Brand70);
                public static SolidColorBrush Brand80 { get; } = new SolidColorBrush(Colors.Global.Dark.Brand80);
                public static SolidColorBrush Brand90 { get; } = new SolidColorBrush(Colors.Global.Dark.Brand90);
                public static SolidColorBrush Brand100 { get; } = new SolidColorBrush(Colors.Global.Dark.Brand100);
                public static SolidColorBrush Green10 { get; } = new SolidColorBrush(Colors.Global.Dark.Green10);
                public static SolidColorBrush Green20 { get; } = new SolidColorBrush(Colors.Global.Dark.Green20);
                public static SolidColorBrush Green30 { get; } = new SolidColorBrush(Colors.Global.Dark.Green30);
                public static SolidColorBrush Green40 { get; } = new SolidColorBrush(Colors.Global.Dark.Green40);
                public static SolidColorBrush Green50 { get; } = new SolidColorBrush(Colors.Global.Dark.Green50);
                public static SolidColorBrush Green60 { get; } = new SolidColorBrush(Colors.Global.Dark.Green60);
                public static SolidColorBrush Green70 { get; } = new SolidColorBrush(Colors.Global.Dark.Green70);
                public static SolidColorBrush Green80 { get; } = new SolidColorBrush(Colors.Global.Dark.Green80);
                public static SolidColorBrush Green90 { get; } = new SolidColorBrush(Colors.Global.Dark.Green90);
                public static SolidColorBrush Green100 { get; } = new SolidColorBrush(Colors.Global.Dark.Green100);
                public static SolidColorBrush Yellow10 { get; } = new SolidColorBrush(Colors.Global.Dark.Yellow10);
                public static SolidColorBrush Yellow20 { get; } = new SolidColorBrush(Colors.Global.Dark.Yellow20);
                public static SolidColorBrush Yellow30 { get; } = new SolidColorBrush(Colors.Global.Dark.Yellow30);
                public static SolidColorBrush Yellow40 { get; } = new SolidColorBrush(Colors.Global.Dark.Yellow40);
                public static SolidColorBrush Yellow50 { get; } = new SolidColorBrush(Colors.Global.Dark.Yellow50);
                public static SolidColorBrush Yellow60 { get; } = new SolidColorBrush(Colors.Global.Dark.Yellow60);
                public static SolidColorBrush Yellow70 { get; } = new SolidColorBrush(Colors.Global.Dark.Yellow70);
                public static SolidColorBrush Yellow80 { get; } = new SolidColorBrush(Colors.Global.Dark.Yellow80);
                public static SolidColorBrush Yellow90 { get; } = new SolidColorBrush(Colors.Global.Dark.Yellow90);
                public static SolidColorBrush Yellow100 { get; } = new SolidColorBrush(Colors.Global.Dark.Yellow100);
                public static SolidColorBrush Red10 { get; } = new SolidColorBrush(Colors.Global.Dark.Red10);
                public static SolidColorBrush Red20 { get; } = new SolidColorBrush(Colors.Global.Dark.Red20);
                public static SolidColorBrush Red30 { get; } = new SolidColorBrush(Colors.Global.Dark.Red30);
                public static SolidColorBrush Red40 { get; } = new SolidColorBrush(Colors.Global.Dark.Red40);
                public static SolidColorBrush Red50 { get; } = new SolidColorBrush(Colors.Global.Dark.Red50);
                public static SolidColorBrush Red60 { get; } = new SolidColorBrush(Colors.Global.Dark.Red60);
                public static SolidColorBrush Red70 { get; } = new SolidColorBrush(Colors.Global.Dark.Red70);
                public static SolidColorBrush Red80 { get; } = new SolidColorBrush(Colors.Global.Dark.Red80);
                public static SolidColorBrush Red90 { get; } = new SolidColorBrush(Colors.Global.Dark.Red90);
                public static SolidColorBrush Red100 { get; } = new SolidColorBrush(Colors.Global.Dark.Red100);
                public static SolidColorBrush Blue10 { get; } = new SolidColorBrush(Colors.Global.Dark.Blue10);
                public static SolidColorBrush Blue20 { get; } = new SolidColorBrush(Colors.Global.Dark.Blue20);
                public static SolidColorBrush Blue30 { get; } = new SolidColorBrush(Colors.Global.Dark.Blue30);
                public static SolidColorBrush Blue40 { get; } = new SolidColorBrush(Colors.Global.Dark.Blue40);
                public static SolidColorBrush Blue50 { get; } = new SolidColorBrush(Colors.Global.Dark.Blue50);
                public static SolidColorBrush Blue60 { get; } = new SolidColorBrush(Colors.Global.Dark.Blue60);
                public static SolidColorBrush Blue70 { get; } = new SolidColorBrush(Colors.Global.Dark.Blue70);
                public static SolidColorBrush Blue80 { get; } = new SolidColorBrush(Colors.Global.Dark.Blue80);
                public static SolidColorBrush Blue90 { get; } = new SolidColorBrush(Colors.Global.Dark.Blue90);
                public static SolidColorBrush Blue100 { get; } = new SolidColorBrush(Colors.Global.Dark.Blue100);
            }

            public static Brush White => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.White : Colors.Global.Dark.White);
            public static Brush Grey10 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Grey10 : Colors.Global.Dark.Grey10);
            public static Brush Grey20 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Grey20 : Colors.Global.Dark.Grey20);
            public static Brush Grey30 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Grey30 : Colors.Global.Dark.Grey30);
            public static Brush Grey40 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Grey40 : Colors.Global.Dark.Grey40);
            public static Brush Grey50 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Grey50 : Colors.Global.Dark.Grey50);
            public static Brush Grey60 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Grey60 : Colors.Global.Dark.Grey60);
            public static Brush Grey70 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Grey70 : Colors.Global.Dark.Grey70);
            public static Brush Grey80 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Grey80 : Colors.Global.Dark.Grey80);
            public static Brush Grey90 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Grey90 : Colors.Global.Dark.Grey90);
            public static Brush Grey100 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Grey100 : Colors.Global.Dark.Grey100);
            public static Brush Brand10 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Brand10 : Colors.Global.Dark.Brand10);
            public static Brush Brand20 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Brand20 : Colors.Global.Dark.Brand20);
            public static Brush Brand30 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Brand30 : Colors.Global.Dark.Brand30);
            public static Brush Brand40 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Brand40 : Colors.Global.Dark.Brand40);
            public static Brush Brand50 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Brand50 : Colors.Global.Dark.Brand50);
            public static Brush Brand60 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Brand60 : Colors.Global.Dark.Brand60);
            public static Brush Brand70 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Brand70 : Colors.Global.Dark.Brand70);
            public static Brush Brand80 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Brand80 : Colors.Global.Dark.Brand80);
            public static Brush Brand90 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Brand90 : Colors.Global.Dark.Brand90);
            public static Brush Brand100 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Brand100 : Colors.Global.Dark.Brand100);
            public static Brush Green10 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Green10 : Colors.Global.Dark.Green10);
            public static Brush Green20 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Green20 : Colors.Global.Dark.Green20);
            public static Brush Green30 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Green30 : Colors.Global.Dark.Green30);
            public static Brush Green40 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Green40 : Colors.Global.Dark.Green40);
            public static Brush Green50 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Green50 : Colors.Global.Dark.Green50);
            public static Brush Green60 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Green60 : Colors.Global.Dark.Green60);
            public static Brush Green70 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Green70 : Colors.Global.Dark.Green70);
            public static Brush Green80 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Green80 : Colors.Global.Dark.Green80);
            public static Brush Green90 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Green90 : Colors.Global.Dark.Green90);
            public static Brush Green100 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Green100 : Colors.Global.Dark.Green100);
            public static Brush Yellow10 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Yellow10 : Colors.Global.Dark.Yellow10);
            public static Brush Yellow20 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Yellow20 : Colors.Global.Dark.Yellow20);
            public static Brush Yellow30 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Yellow30 : Colors.Global.Dark.Yellow30);
            public static Brush Yellow40 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Yellow40 : Colors.Global.Dark.Yellow40);
            public static Brush Yellow50 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Yellow50 : Colors.Global.Dark.Yellow50);
            public static Brush Yellow60 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Yellow60 : Colors.Global.Dark.Yellow60);
            public static Brush Yellow70 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Yellow70 : Colors.Global.Dark.Yellow70);
            public static Brush Yellow80 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Yellow80 : Colors.Global.Dark.Yellow80);
            public static Brush Yellow90 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Yellow90 : Colors.Global.Dark.Yellow90);
            public static Brush Yellow100 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Yellow100 : Colors.Global.Dark.Yellow100);
            public static Brush Red10 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Red10 : Colors.Global.Dark.Red10);
            public static Brush Red20 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Red20 : Colors.Global.Dark.Red20);
            public static Brush Red30 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Red30 : Colors.Global.Dark.Red30);
            public static Brush Red40 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Red40 : Colors.Global.Dark.Red40);
            public static Brush Red50 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Red50 : Colors.Global.Dark.Red50);
            public static Brush Red60 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Red60 : Colors.Global.Dark.Red60);
            public static Brush Red70 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Red70 : Colors.Global.Dark.Red70);
            public static Brush Red80 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Red80 : Colors.Global.Dark.Red80);
            public static Brush Red90 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Red90 : Colors.Global.Dark.Red90);
            public static Brush Red100 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Red100 : Colors.Global.Dark.Red100);
            public static Brush Blue10 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Blue10 : Colors.Global.Dark.Blue10);
            public static Brush Blue20 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Blue20 : Colors.Global.Dark.Blue20);
            public static Brush Blue30 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Blue30 : Colors.Global.Dark.Blue30);
            public static Brush Blue40 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Blue40 : Colors.Global.Dark.Blue40);
            public static Brush Blue50 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Blue50 : Colors.Global.Dark.Blue50);
            public static Brush Blue60 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Blue60 : Colors.Global.Dark.Blue60);
            public static Brush Blue70 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Blue70 : Colors.Global.Dark.Blue70);
            public static Brush Blue80 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Blue80 : Colors.Global.Dark.Blue80);
            public static Brush Blue90 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Blue90 : Colors.Global.Dark.Blue90);
            public static Brush Blue100 => new SolidColorBrush(IsLightTheme ? Colors.Global.Light.Blue100 : Colors.Global.Dark.Blue100);
        }

        public static class Semantic
        {
            public static class Light
            {
                public static SolidColorBrush FgBase { get; } = new SolidColorBrush(Colors.Semantic.Light.FgBase);
                public static SolidColorBrush FgMuted { get; } = new SolidColorBrush(Colors.Semantic.Light.FgMuted);
                public static SolidColorBrush FgSubtle { get; } = new SolidColorBrush(Colors.Semantic.Light.FgSubtle);
                public static SolidColorBrush FgLink { get; } = new SolidColorBrush(Colors.Semantic.Light.FgLink);
                public static SolidColorBrush FgDisabled { get; } = new SolidColorBrush(Colors.Semantic.Light.FgDisabled);
                public static SolidColorBrush FgOnContrast { get; } = new SolidColorBrush(Colors.Semantic.Light.FgOnContrast);
                public static SolidColorBrush FgStaticDark { get; } = new SolidColorBrush(Colors.Semantic.Light.FgStaticDark);
                public static SolidColorBrush FgStaticLight { get; } = new SolidColorBrush(Colors.Semantic.Light.FgStaticLight);
                public static SolidColorBrush FgDanger { get; } = new SolidColorBrush(Colors.Semantic.Light.FgDanger);
                public static SolidColorBrush FgSuccess { get; } = new SolidColorBrush(Colors.Semantic.Light.FgSuccess);
                public static SolidColorBrush FgWarning { get; } = new SolidColorBrush(Colors.Semantic.Light.FgWarning);
                public static SolidColorBrush FgError { get; } = new SolidColorBrush(Colors.Semantic.Light.FgError);
                public static SolidColorBrush FgInfo { get; } = new SolidColorBrush(Colors.Semantic.Light.FgInfo);
                public static SolidColorBrush BgCanvas { get; } = new SolidColorBrush(Colors.Semantic.Light.BgCanvas);
                public static SolidColorBrush BgSubtle { get; } = new SolidColorBrush(Colors.Semantic.Light.BgSubtle);
                public static SolidColorBrush BgMuted { get; } = new SolidColorBrush(Colors.Semantic.Light.BgMuted);
                public static SolidColorBrush BgContrast { get; } = new SolidColorBrush(Colors.Semantic.Light.BgContrast);
                public static SolidColorBrush BgSurface { get; } = new SolidColorBrush(Colors.Semantic.Light.BgSurface);
                public static SolidColorBrush BgInteractivePrimary { get; } = new SolidColorBrush(Colors.Semantic.Light.BgInteractivePrimary);
                public static SolidColorBrush BgInteractiveSecondary { get; } = new SolidColorBrush(Colors.Semantic.Light.BgInteractiveSecondary);
                public static SolidColorBrush BgInteractiveTertiary { get; } = new SolidColorBrush(Colors.Semantic.Light.BgInteractiveTertiary);
                public static SolidColorBrush BgSuccess { get; } = new SolidColorBrush(Colors.Semantic.Light.BgSuccess);
                public static SolidColorBrush BgSuccessContrast { get; } = new SolidColorBrush(Colors.Semantic.Light.BgSuccessContrast);
                public static SolidColorBrush BgError { get; } = new SolidColorBrush(Colors.Semantic.Light.BgError);
                public static SolidColorBrush BgErrorContrast { get; } = new SolidColorBrush(Colors.Semantic.Light.BgErrorContrast);
                public static SolidColorBrush BgWarning { get; } = new SolidColorBrush(Colors.Semantic.Light.BgWarning);
                public static SolidColorBrush BgWarningContrast { get; } = new SolidColorBrush(Colors.Semantic.Light.BgWarningContrast);
                public static SolidColorBrush BgInfo { get; } = new SolidColorBrush(Colors.Semantic.Light.BgInfo);
                public static SolidColorBrush BgInfoContrast { get; } = new SolidColorBrush(Colors.Semantic.Light.BgInfoContrast);
                public static SolidColorBrush BgOverlay { get; } = new SolidColorBrush(Colors.Semantic.Light.BgOverlay);
                public static SolidColorBrush BgNotification { get; } = new SolidColorBrush(Colors.Semantic.Light.BgNotification);
                public static SolidColorBrush BgDisabled { get; } = new SolidColorBrush(Colors.Semantic.Light.BgDisabled);
                public static SolidColorBrush BgDangerPrimary { get; } = new SolidColorBrush(Colors.Semantic.Light.BgDangerPrimary);
                public static SolidColorBrush BgDangerSecondary { get; } = new SolidColorBrush(Colors.Semantic.Light.BgDangerSecondary);
                public static SolidColorBrush BgDangerTertiary { get; } = new SolidColorBrush(Colors.Semantic.Light.BgDangerTertiary);
                public static SolidColorBrush AccentOnAccent { get; } = new SolidColorBrush(Colors.Semantic.Light.AccentOnAccent);
                public static SolidColorBrush AccentSubtle { get; } = new SolidColorBrush(Colors.Semantic.Light.AccentSubtle);
                public static SolidColorBrush AccentMuted { get; } = new SolidColorBrush(Colors.Semantic.Light.AccentMuted);
                public static SolidColorBrush AccentDim { get; } = new SolidColorBrush(Colors.Semantic.Light.AccentDim);
                public static SolidColorBrush AccentModerate { get; } = new SolidColorBrush(Colors.Semantic.Light.AccentModerate);
                public static SolidColorBrush AccentBold { get; } = new SolidColorBrush(Colors.Semantic.Light.AccentBold);
                public static SolidColorBrush AccentStrong { get; } = new SolidColorBrush(Colors.Semantic.Light.AccentStrong);
                public static SolidColorBrush AccentIntense { get; } = new SolidColorBrush(Colors.Semantic.Light.AccentIntense);
                public static SolidColorBrush BorderSubtle { get; } = new SolidColorBrush(Colors.Semantic.Light.BorderSubtle);
                public static SolidColorBrush BorderMuted { get; } = new SolidColorBrush(Colors.Semantic.Light.BorderMuted);
                public static SolidColorBrush BorderInteractivePrimary { get; } = new SolidColorBrush(Colors.Semantic.Light.BorderInteractivePrimary);
                public static SolidColorBrush BorderContrast { get; } = new SolidColorBrush(Colors.Semantic.Light.BorderContrast);
                public static SolidColorBrush BorderDisabled { get; } = new SolidColorBrush(Colors.Semantic.Light.BorderDisabled);
                public static SolidColorBrush BorderError { get; } = new SolidColorBrush(Colors.Semantic.Light.BorderError);
            }

            public static class Dark
            {
                public static SolidColorBrush FgBase { get; } = new SolidColorBrush(Colors.Semantic.Dark.FgBase);
                public static SolidColorBrush FgMuted { get; } = new SolidColorBrush(Colors.Semantic.Dark.FgMuted);
                public static SolidColorBrush FgSubtle { get; } = new SolidColorBrush(Colors.Semantic.Dark.FgSubtle);
                public static SolidColorBrush FgLink { get; } = new SolidColorBrush(Colors.Semantic.Dark.FgLink);
                public static SolidColorBrush FgDisabled { get; } = new SolidColorBrush(Colors.Semantic.Dark.FgDisabled);
                public static SolidColorBrush FgOnContrast { get; } = new SolidColorBrush(Colors.Semantic.Dark.FgOnContrast);
                public static SolidColorBrush FgStaticDark { get; } = new SolidColorBrush(Colors.Semantic.Dark.FgStaticDark);
                public static SolidColorBrush FgStaticLight { get; } = new SolidColorBrush(Colors.Semantic.Dark.FgStaticLight);
                public static SolidColorBrush FgDanger { get; } = new SolidColorBrush(Colors.Semantic.Dark.FgDanger);
                public static SolidColorBrush FgSuccess { get; } = new SolidColorBrush(Colors.Semantic.Dark.FgSuccess);
                public static SolidColorBrush FgWarning { get; } = new SolidColorBrush(Colors.Semantic.Dark.FgWarning);
                public static SolidColorBrush FgError { get; } = new SolidColorBrush(Colors.Semantic.Dark.FgError);
                public static SolidColorBrush FgInfo { get; } = new SolidColorBrush(Colors.Semantic.Dark.FgInfo);
                public static SolidColorBrush BgCanvas { get; } = new SolidColorBrush(Colors.Semantic.Dark.BgCanvas);
                public static SolidColorBrush BgSubtle { get; } = new SolidColorBrush(Colors.Semantic.Dark.BgSubtle);
                public static SolidColorBrush BgMuted { get; } = new SolidColorBrush(Colors.Semantic.Dark.BgMuted);
                public static SolidColorBrush BgContrast { get; } = new SolidColorBrush(Colors.Semantic.Dark.BgContrast);
                public static SolidColorBrush BgSurface { get; } = new SolidColorBrush(Colors.Semantic.Dark.BgSurface);
                public static SolidColorBrush BgInteractivePrimary { get; } = new SolidColorBrush(Colors.Semantic.Dark.BgInteractivePrimary);
                public static SolidColorBrush BgInteractiveSecondary { get; } = new SolidColorBrush(Colors.Semantic.Dark.BgInteractiveSecondary);
                public static SolidColorBrush BgInteractiveTertiary { get; } = new SolidColorBrush(Colors.Semantic.Dark.BgInteractiveTertiary);
                public static SolidColorBrush BgSuccess { get; } = new SolidColorBrush(Colors.Semantic.Dark.BgSuccess);
                public static SolidColorBrush BgSuccessContrast { get; } = new SolidColorBrush(Colors.Semantic.Dark.BgSuccessContrast);
                public static SolidColorBrush BgError { get; } = new SolidColorBrush(Colors.Semantic.Dark.BgError);
                public static SolidColorBrush BgErrorContrast { get; } = new SolidColorBrush(Colors.Semantic.Dark.BgErrorContrast);
                public static SolidColorBrush BgWarning { get; } = new SolidColorBrush(Colors.Semantic.Dark.BgWarning);
                public static SolidColorBrush BgWarningContrast { get; } = new SolidColorBrush(Colors.Semantic.Dark.BgWarningContrast);
                public static SolidColorBrush BgInfo { get; } = new SolidColorBrush(Colors.Semantic.Dark.BgInfo);
                public static SolidColorBrush BgInfoContrast { get; } = new SolidColorBrush(Colors.Semantic.Dark.BgInfoContrast);
                public static SolidColorBrush BgOverlay { get; } = new SolidColorBrush(Colors.Semantic.Dark.BgOverlay);
                public static SolidColorBrush BgNotification { get; } = new SolidColorBrush(Colors.Semantic.Dark.BgNotification);
                public static SolidColorBrush BgDisabled { get; } = new SolidColorBrush(Colors.Semantic.Dark.BgDisabled);
                public static SolidColorBrush BgDangerPrimary { get; } = new SolidColorBrush(Colors.Semantic.Dark.BgDangerPrimary);
                public static SolidColorBrush BgDangerSecondary { get; } = new SolidColorBrush(Colors.Semantic.Dark.BgDangerSecondary);
                public static SolidColorBrush BgDangerTertiary { get; } = new SolidColorBrush(Colors.Semantic.Dark.BgDangerTertiary);
                public static SolidColorBrush AccentOnAccent { get; } = new SolidColorBrush(Colors.Semantic.Dark.AccentOnAccent);
                public static SolidColorBrush AccentSubtle { get; } = new SolidColorBrush(Colors.Semantic.Dark.AccentSubtle);
                public static SolidColorBrush AccentMuted { get; } = new SolidColorBrush(Colors.Semantic.Dark.AccentMuted);
                public static SolidColorBrush AccentDim { get; } = new SolidColorBrush(Colors.Semantic.Dark.AccentDim);
                public static SolidColorBrush AccentModerate { get; } = new SolidColorBrush(Colors.Semantic.Dark.AccentModerate);
                public static SolidColorBrush AccentBold { get; } = new SolidColorBrush(Colors.Semantic.Dark.AccentBold);
                public static SolidColorBrush AccentStrong { get; } = new SolidColorBrush(Colors.Semantic.Dark.AccentStrong);
                public static SolidColorBrush AccentIntense { get; } = new SolidColorBrush(Colors.Semantic.Dark.AccentIntense);
                public static SolidColorBrush BorderSubtle { get; } = new SolidColorBrush(Colors.Semantic.Dark.BorderSubtle);
                public static SolidColorBrush BorderMuted { get; } = new SolidColorBrush(Colors.Semantic.Dark.BorderMuted);
                public static SolidColorBrush BorderInteractivePrimary { get; } = new SolidColorBrush(Colors.Semantic.Dark.BorderInteractivePrimary);
                public static SolidColorBrush BorderContrast { get; } = new SolidColorBrush(Colors.Semantic.Dark.BorderContrast);
                public static SolidColorBrush BorderDisabled { get; } = new SolidColorBrush(Colors.Semantic.Dark.BorderDisabled);
                public static SolidColorBrush BorderError { get; } = new SolidColorBrush(Colors.Semantic.Dark.BorderError);
            }

            public static Brush FgBase => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.FgBase : Colors.Semantic.Dark.FgBase);
            public static Brush FgMuted => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.FgMuted : Colors.Semantic.Dark.FgMuted);
            public static Brush FgSubtle => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.FgSubtle : Colors.Semantic.Dark.FgSubtle);
            public static Brush FgLink => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.FgLink : Colors.Semantic.Dark.FgLink);
            public static Brush FgDisabled => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.FgDisabled : Colors.Semantic.Dark.FgDisabled);
            public static Brush FgOnContrast => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.FgOnContrast : Colors.Semantic.Dark.FgOnContrast);
            public static Brush FgStaticDark => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.FgStaticDark : Colors.Semantic.Dark.FgStaticDark);
            public static Brush FgStaticLight => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.FgStaticLight : Colors.Semantic.Dark.FgStaticLight);
            public static Brush FgDanger => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.FgDanger : Colors.Semantic.Dark.FgDanger);
            public static Brush FgSuccess => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.FgSuccess : Colors.Semantic.Dark.FgSuccess);
            public static Brush FgWarning => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.FgWarning : Colors.Semantic.Dark.FgWarning);
            public static Brush FgError => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.FgError : Colors.Semantic.Dark.FgError);
            public static Brush FgInfo => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.FgInfo : Colors.Semantic.Dark.FgInfo);
            public static Brush BgCanvas => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BgCanvas : Colors.Semantic.Dark.BgCanvas);
            public static Brush BgSubtle => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BgSubtle : Colors.Semantic.Dark.BgSubtle);
            public static Brush BgMuted => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BgMuted : Colors.Semantic.Dark.BgMuted);
            public static Brush BgContrast => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BgContrast : Colors.Semantic.Dark.BgContrast);
            public static Brush BgSurface => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BgSurface : Colors.Semantic.Dark.BgSurface);
            public static Brush BgInteractivePrimary => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BgInteractivePrimary : Colors.Semantic.Dark.BgInteractivePrimary);
            public static Brush BgInteractiveSecondary => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BgInteractiveSecondary : Colors.Semantic.Dark.BgInteractiveSecondary);
            public static Brush BgInteractiveTertiary => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BgInteractiveTertiary : Colors.Semantic.Dark.BgInteractiveTertiary);
            public static Brush BgSuccess => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BgSuccess : Colors.Semantic.Dark.BgSuccess);
            public static Brush BgSuccessContrast => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BgSuccessContrast : Colors.Semantic.Dark.BgSuccessContrast);
            public static Brush BgError => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BgError : Colors.Semantic.Dark.BgError);
            public static Brush BgErrorContrast => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BgErrorContrast : Colors.Semantic.Dark.BgErrorContrast);
            public static Brush BgWarning => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BgWarning : Colors.Semantic.Dark.BgWarning);
            public static Brush BgWarningContrast => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BgWarningContrast : Colors.Semantic.Dark.BgWarningContrast);
            public static Brush BgInfo => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BgInfo : Colors.Semantic.Dark.BgInfo);
            public static Brush BgInfoContrast => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BgInfoContrast : Colors.Semantic.Dark.BgInfoContrast);
            public static Brush BgOverlay => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BgOverlay : Colors.Semantic.Dark.BgOverlay);
            public static Brush BgNotification => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BgNotification : Colors.Semantic.Dark.BgNotification);
            public static Brush BgDisabled => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BgDisabled : Colors.Semantic.Dark.BgDisabled);
            public static Brush BgDangerPrimary => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BgDangerPrimary : Colors.Semantic.Dark.BgDangerPrimary);
            public static Brush BgDangerSecondary => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BgDangerSecondary : Colors.Semantic.Dark.BgDangerSecondary);
            public static Brush BgDangerTertiary => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BgDangerTertiary : Colors.Semantic.Dark.BgDangerTertiary);
            public static Brush AccentOnAccent => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.AccentOnAccent : Colors.Semantic.Dark.AccentOnAccent);
            public static Brush AccentSubtle => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.AccentSubtle : Colors.Semantic.Dark.AccentSubtle);
            public static Brush AccentMuted => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.AccentMuted : Colors.Semantic.Dark.AccentMuted);
            public static Brush AccentDim => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.AccentDim : Colors.Semantic.Dark.AccentDim);
            public static Brush AccentModerate => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.AccentModerate : Colors.Semantic.Dark.AccentModerate);
            public static Brush AccentBold => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.AccentBold : Colors.Semantic.Dark.AccentBold);
            public static Brush AccentStrong => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.AccentStrong : Colors.Semantic.Dark.AccentStrong);
            public static Brush AccentIntense => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.AccentIntense : Colors.Semantic.Dark.AccentIntense);
            public static Brush BorderSubtle => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BorderSubtle : Colors.Semantic.Dark.BorderSubtle);
            public static Brush BorderMuted => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BorderMuted : Colors.Semantic.Dark.BorderMuted);
            public static Brush BorderInteractivePrimary => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BorderInteractivePrimary : Colors.Semantic.Dark.BorderInteractivePrimary);
            public static Brush BorderContrast => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BorderContrast : Colors.Semantic.Dark.BorderContrast);
            public static Brush BorderDisabled => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BorderDisabled : Colors.Semantic.Dark.BorderDisabled);
            public static Brush BorderError => new SolidColorBrush(IsLightTheme ? Colors.Semantic.Light.BorderError : Colors.Semantic.Dark.BorderError);

        }
    }

}
